# Generated by Django 2.1.7 on 2019-03-30 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='place_birth',
            new_name='birthplace',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='year_born',
            new_name='born',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='year_published',
            new_name='published',
        ),
    ]
