# Generated by Django 2.1.7 on 2019-03-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20190330_2232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
