# Generated by Django 2.1.7 on 2019-04-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_auto_20190401_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
