# Generated by Django 2.1.7 on 2019-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_blog_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro',
            field=models.TextField(),
        ),
    ]
