# Generated by Django 2.1.7 on 2019-04-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20190401_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
