# Generated by Django 2.1.7 on 2019-04-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_auto_20190406_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
