# Generated by Django 2.1.7 on 2019-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_auto_20190406_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
