# Generated by Django 2.1.7 on 2019-04-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0016_auto_20190406_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_post',
            new_name='post',
        ),
    ]
