# Generated by Django 2.1.7 on 2019-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0017_auto_20190406_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
