# Generated by Django 2.1.7 on 2019-04-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0018_auto_20190406_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
